import { fetchApi } from './fetch'
/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type {
  AppConfig,
  AppEvent,
  CodexAuthStatus,
  CodexDeviceLogin,
  CodexImageGenerationOptions,
  CodexImageGenerationResponse,
  ConfigPatch,
  CreatePagesFromPathsRequest,
  CreatePagesResponse,
  CreateProjectRequest,
  EngineCatalog,
  ExportProjectRequest,
  FontFaceInfo,
  GoogleFontCatalog,
  HistoryResult,
  ListDownloadsResponse,
  ListOperationsResponse,
  ListProjectsResponse,
  LlmCatalog,
  LlmLoadRequest,
  LlmState,
  MaskRole,
  MetaInfo,
  Op,
  OpenProjectRequest,
  PageId,
  ProjectSummary,
  ProviderSecretRequest,
  PutMaskParams,
  PutMaskResponse,
  ReadingOrder,
  SceneSnapshot,
  StartDownloadRequest,
  StartDownloadResponse,
  StartPipelineRequest,
  StartPipelineResponse,
} from './schemas'
export const getStartCodexDeviceLoginUrl = () => {
  return `/api/v1/ai/codex/auth/device-code`
}

export const startCodexDeviceLogin = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<CodexDeviceLogin> => {
  return fetchApi<CodexDeviceLogin>(getStartCodexDeviceLoginUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getDeleteCodexSessionUrl = () => {
  return `/api/v1/ai/codex/auth/session`
}

export const deleteCodexSession = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<void> => {
  return fetchApi<void>(getDeleteCodexSessionUrl(), {
    ...options,
    method: 'DELETE',
  })
}

export const getGetCodexAuthStatusUrl = () => {
  return `/api/v1/ai/codex/auth/status`
}

export const getCodexAuthStatus = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<CodexAuthStatus> => {
  return fetchApi<CodexAuthStatus>(getGetCodexAuthStatusUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getStartCodexImageGenerationUrl = () => {
  return `/api/v1/ai/codex/images`
}

export const startCodexImageGeneration = async (
  codexImageGenerationOptions: CodexImageGenerationOptions,
  options?: Parameters<typeof fetchApi>[1],
): Promise<CodexImageGenerationResponse> => {
  return fetchApi<CodexImageGenerationResponse>(getStartCodexImageGenerationUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(codexImageGenerationOptions),
  })
}

export const getGetBlobUrl = (hash: string) => {
  return `/api/v1/blobs/${hash}`
}

export const getBlob = async (
  hash: string,
  options?: Parameters<typeof fetchApi>[1],
): Promise<Blob> => {
  return fetchApi<Blob>(getGetBlobUrl(hash), {
    ...options,
    method: 'GET',
  })
}

export const getGetConfigUrl = () => {
  return `/api/v1/config`
}

export const getConfig = async (options?: Parameters<typeof fetchApi>[1]): Promise<AppConfig> => {
  return fetchApi<AppConfig>(getGetConfigUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getPatchConfigUrl = () => {
  return `/api/v1/config`
}

export const patchConfig = async (
  configPatch: ConfigPatch,
  options?: Parameters<typeof fetchApi>[1],
): Promise<AppConfig> => {
  return fetchApi<AppConfig>(getPatchConfigUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(configPatch),
  })
}

export const getSetProviderSecretUrl = (id: string) => {
  return `/api/v1/config/providers/${id}/secret`
}

/**
 * @summary Save (or overwrite) the keyring secret for a provider. Creates the
provider entry in `config.providers` if it didn't exist. `PUT` because
setting the secret is idempotent for the same body.
 */
export const setProviderSecret = async (
  id: string,
  providerSecretRequest: ProviderSecretRequest,
  options?: Parameters<typeof fetchApi>[1],
): Promise<void> => {
  return fetchApi<void>(getSetProviderSecretUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(providerSecretRequest),
  })
}

export const getClearProviderSecretUrl = (id: string) => {
  return `/api/v1/config/providers/${id}/secret`
}

/**
 * @summary Clear a provider's keyring secret. The provider entry itself is kept.
 */
export const clearProviderSecret = async (
  id: string,
  options?: Parameters<typeof fetchApi>[1],
): Promise<void> => {
  return fetchApi<void>(getClearProviderSecretUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getListDownloadsUrl = () => {
  return `/api/v1/downloads`
}

export const listDownloads = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<ListDownloadsResponse> => {
  return fetchApi<ListDownloadsResponse>(getListDownloadsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getStartDownloadUrl = () => {
  return `/api/v1/downloads`
}

export const startDownload = async (
  startDownloadRequest: StartDownloadRequest,
  options?: Parameters<typeof fetchApi>[1],
): Promise<StartDownloadResponse> => {
  return fetchApi<StartDownloadResponse>(getStartDownloadUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(startDownloadRequest),
  })
}

export const getGetEngineCatalogUrl = () => {
  return `/api/v1/engines`
}

export const getEngineCatalog = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<EngineCatalog> => {
  return fetchApi<EngineCatalog>(getGetEngineCatalogUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getEventsUrl = () => {
  return `/api/v1/events`
}

export const events = async (options?: Parameters<typeof fetchApi>[1]): Promise<AppEvent> => {
  return fetchApi<AppEvent>(getEventsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getListFontsUrl = () => {
  return `/api/v1/fonts`
}

export const listFonts = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<FontFaceInfo[]> => {
  return fetchApi<FontFaceInfo[]>(getListFontsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetGoogleFontsCatalogUrl = () => {
  return `/api/v1/google-fonts`
}

export const getGoogleFontsCatalog = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<GoogleFontCatalog> => {
  return fetchApi<GoogleFontCatalog>(getGetGoogleFontsCatalogUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getFetchGoogleFontUrl = (family: string) => {
  return `/api/v1/google-fonts/${family}/fetch`
}

export const fetchGoogleFont = async (
  family: string,
  options?: Parameters<typeof fetchApi>[1],
): Promise<void> => {
  return fetchApi<void>(getFetchGoogleFontUrl(family), {
    ...options,
    method: 'POST',
  })
}

export const getGetGoogleFontFileUrl = (family: string, file: string) => {
  return `/api/v1/google-fonts/${family}/${file}`
}

export const getGoogleFontFile = async (
  family: string,
  file: string,
  options?: Parameters<typeof fetchApi>[1],
): Promise<Blob> => {
  return fetchApi<Blob>(getGetGoogleFontFileUrl(family, file), {
    ...options,
    method: 'GET',
  })
}

export const getApplyCommandUrl = () => {
  return `/api/v1/history/apply`
}

export const applyCommand = async (
  op: Op,
  options?: Parameters<typeof fetchApi>[1],
): Promise<HistoryResult> => {
  return fetchApi<HistoryResult>(getApplyCommandUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(op),
  })
}

export const getRedoUrl = () => {
  return `/api/v1/history/redo`
}

export const redo = async (options?: Parameters<typeof fetchApi>[1]): Promise<HistoryResult> => {
  return fetchApi<HistoryResult>(getRedoUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getUndoUrl = () => {
  return `/api/v1/history/undo`
}

export const undo = async (options?: Parameters<typeof fetchApi>[1]): Promise<HistoryResult> => {
  return fetchApi<HistoryResult>(getUndoUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getGetCatalogUrl = () => {
  return `/api/v1/llm/catalog`
}

export const getCatalog = async (options?: Parameters<typeof fetchApi>[1]): Promise<LlmCatalog> => {
  return fetchApi<LlmCatalog>(getGetCatalogUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetCurrentLlmUrl = () => {
  return `/api/v1/llm/current`
}

export const getCurrentLlm = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<LlmState> => {
  return fetchApi<LlmState>(getGetCurrentLlmUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getPutCurrentLlmUrl = () => {
  return `/api/v1/llm/current`
}

export const putCurrentLlm = async (
  llmLoadRequest: LlmLoadRequest,
  options?: Parameters<typeof fetchApi>[1],
): Promise<void> => {
  return fetchApi<void>(getPutCurrentLlmUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(llmLoadRequest),
  })
}

export const getDeleteCurrentLlmUrl = () => {
  return `/api/v1/llm/current`
}

export const deleteCurrentLlm = async (options?: Parameters<typeof fetchApi>[1]): Promise<void> => {
  return fetchApi<void>(getDeleteCurrentLlmUrl(), {
    ...options,
    method: 'DELETE',
  })
}

export const getGetMetaUrl = () => {
  return `/api/v1/meta`
}

export const getMeta = async (options?: Parameters<typeof fetchApi>[1]): Promise<MetaInfo> => {
  return fetchApi<MetaInfo>(getGetMetaUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getListOperationsUrl = () => {
  return `/api/v1/operations`
}

export const listOperations = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<ListOperationsResponse> => {
  return fetchApi<ListOperationsResponse>(getListOperationsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getCancelOperationUrl = (id: string) => {
  return `/api/v1/operations/${id}`
}

export const cancelOperation = async (
  id: string,
  options?: Parameters<typeof fetchApi>[1],
): Promise<void> => {
  return fetchApi<void>(getCancelOperationUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getCreatePagesUrl = () => {
  return `/api/v1/pages`
}

export const createPages = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<CreatePagesResponse> => {
  return fetchApi<CreatePagesResponse>(getCreatePagesUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getCreatePagesFromPathsUrl = () => {
  return `/api/v1/pages/from-paths`
}

/**
 * Web clients should keep using `POST /pages` with multipart.
 * @summary Create pages by reading image files from absolute paths on the server's
filesystem. This is the Tauri desktop import path — the webview picker
returns paths, and the backend reads + decodes + hashes them in parallel
without a round-trip through JS memory or a multipart upload body.
 */
export const createPagesFromPaths = async (
  createPagesFromPathsRequest: CreatePagesFromPathsRequest,
  options?: Parameters<typeof fetchApi>[1],
): Promise<CreatePagesResponse> => {
  return fetchApi<CreatePagesResponse>(getCreatePagesFromPathsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPagesFromPathsRequest),
  })
}

export const getPutMaskUrl = (id: PageId, role: MaskRole, params?: PutMaskParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/pages/${id}/masks/${role}?${stringifiedParams}`
    : `/api/v1/pages/${id}/masks/${role}`
}

/**
 * @summary Upsert the `Mask { role }` node on a page with the raw image bytes in
the body. Emits `Op::UpdateNode` if a mask of that role exists, else
`Op::AddNode`. Used by the repair-brush / segment-edit flow; the
follow-up localized inpaint is a separate `POST /pipelines` call.
 */
export const putMask = async (
  id: PageId,
  role: MaskRole,
  putMaskBody?: Blob,
  params?: PutMaskParams,
  options?: Parameters<typeof fetchApi>[1],
): Promise<PutMaskResponse> => {
  return fetchApi<PutMaskResponse>(getPutMaskUrl(id, role, params), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'image/png', ...options?.headers },
    body: putMaskBody,
  })
}

export const getGetPageThumbnailUrl = (id: PageId) => {
  return `/api/v1/pages/${id}/thumbnail`
}

export const getPageThumbnail = async (
  id: PageId,
  options?: Parameters<typeof fetchApi>[1],
): Promise<Blob> => {
  return fetchApi<Blob>(getGetPageThumbnailUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getReorderTextNodesUrl = (pageId: PageId) => {
  return `/api/v1/pages/${pageId}/reorder-text-nodes`
}

export const reorderTextNodes = async (
  pageId: PageId,
  readingOrder: ReadingOrder,
  options?: Parameters<typeof fetchApi>[1],
): Promise<void> => {
  return fetchApi<void>(getReorderTextNodesUrl(pageId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(readingOrder),
  })
}

export const getStartPipelineUrl = () => {
  return `/api/v1/pipelines`
}

export const startPipeline = async (
  startPipelineRequest: StartPipelineRequest,
  options?: Parameters<typeof fetchApi>[1],
): Promise<StartPipelineResponse> => {
  return fetchApi<StartPipelineResponse>(getStartPipelineUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(startPipelineRequest),
  })
}

export const getListProjectsUrl = () => {
  return `/api/v1/projects`
}

export const listProjects = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<ListProjectsResponse> => {
  return fetchApi<ListProjectsResponse>(getListProjectsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getCreateProjectUrl = () => {
  return `/api/v1/projects`
}

export const createProject = async (
  createProjectRequest: CreateProjectRequest,
  options?: Parameters<typeof fetchApi>[1],
): Promise<ProjectSummary> => {
  return fetchApi<ProjectSummary>(getCreateProjectUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProjectRequest),
  })
}

export const getPutCurrentProjectUrl = () => {
  return `/api/v1/projects/current`
}

export const putCurrentProject = async (
  openProjectRequest: OpenProjectRequest,
  options?: Parameters<typeof fetchApi>[1],
): Promise<ProjectSummary> => {
  return fetchApi<ProjectSummary>(getPutCurrentProjectUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(openProjectRequest),
  })
}

export const getDeleteCurrentProjectUrl = () => {
  return `/api/v1/projects/current`
}

export const deleteCurrentProject = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<void> => {
  return fetchApi<void>(getDeleteCurrentProjectUrl(), {
    ...options,
    method: 'DELETE',
  })
}

export const getExportCurrentProjectUrl = () => {
  return `/api/v1/projects/current/export`
}

export const exportCurrentProject = async (
  exportProjectRequest: ExportProjectRequest,
  options?: Parameters<typeof fetchApi>[1],
): Promise<Blob> => {
  return fetchApi<Blob>(getExportCurrentProjectUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exportProjectRequest),
  })
}

export const getImportProjectUrl = () => {
  return `/api/v1/projects/import`
}

export const importProject = async (
  importProjectBody?: Blob,
  options?: Parameters<typeof fetchApi>[1],
): Promise<ProjectSummary> => {
  return fetchApi<ProjectSummary>(getImportProjectUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/zip', ...options?.headers },
    body: importProjectBody,
  })
}

export const getDeleteProjectUrl = (id: string) => {
  return `/api/v1/projects/${id}`
}

export const deleteProject = async (
  id: string,
  options?: Parameters<typeof fetchApi>[1],
): Promise<void> => {
  return fetchApi<void>(getDeleteProjectUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getGetSceneBinUrl = () => {
  return `/api/v1/scene.bin`
}

export const getSceneBin = async (options?: Parameters<typeof fetchApi>[1]): Promise<Blob> => {
  return fetchApi<Blob>(getGetSceneBinUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetSceneJsonUrl = () => {
  return `/api/v1/scene.json`
}

export const getSceneJson = async (
  options?: Parameters<typeof fetchApi>[1],
): Promise<SceneSnapshot> => {
  return fetchApi<SceneSnapshot>(getGetSceneJsonUrl(), {
    ...options,
    method: 'GET',
  })
}
