/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

/**
 * Hex-encoded blake3 hash of an immutable blob.
 * @minLength 64
 * @maxLength 64
 * @pattern ^[0-9a-f]{64}$
 */
export type BlobRef = string
