/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { CodexDeviceLoginStatus } from './codexDeviceLoginStatus'

export interface CodexAuthStatus {
  /** @nullable */
  accountId?: string | null
  login?: null | CodexDeviceLoginStatus
  signedIn: boolean
}
