/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { GoogleFontVariant } from './googleFontVariant'

export interface GoogleFontEntry {
  category: string
  family: string
  subsets: string[]
  variants: GoogleFontVariant[]
}
