/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { JobStatus } from './jobStatus'

export interface JobFinishedEvent {
  /** @nullable */
  error?: string | null
  id: string
  status: JobStatus
}
