/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { LlmCatalogModel } from './llmCatalogModel'
import type { LlmProviderCatalog } from './llmProviderCatalog'

export interface LlmCatalog {
  localModels: LlmCatalogModel[]
  providers: LlmProviderCatalog[]
}
