/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export type LlmProviderCatalogStatus =
  (typeof LlmProviderCatalogStatus)[keyof typeof LlmProviderCatalogStatus]

export const LlmProviderCatalogStatus = {
  ready: 'ready',
  missing_configuration: 'missing_configuration',
  discovery_failed: 'discovery_failed',
} as const
