/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export type LlmStateStatus = (typeof LlmStateStatus)[keyof typeof LlmStateStatus]

export const LlmStateStatus = {
  empty: 'empty',
  loading: 'loading',
  ready: 'ready',
  failed: 'failed',
} as const
