/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { LlmTargetKind } from './llmTargetKind'

export interface LlmTarget {
  kind: LlmTargetKind
  modelId: string
  /** @nullable */
  providerId?: string | null
}
