/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { BlobRef } from './blobRef'
import type { MaskRole } from './maskRole'

export interface MaskData {
  blob: BlobRef
  role: MaskRole
}
