/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { ImageDataPatch } from './imageDataPatch'
import type { MaskDataPatch } from './maskDataPatch'
import type { TextDataPatch } from './textDataPatch'

export type NodeDataPatch =
  | {
      text: TextDataPatch
    }
  | {
      image: ImageDataPatch
    }
  | {
      mask: MaskDataPatch
    }
