/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export interface OpenProjectRequest {
  /**
   * `.khrproj/` directory basename (no extension). Must exist under the
   * managed projects directory.
   */
  id: string
}
