/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { SourceTextPolicy } from './sourceTextPolicy'

/**
 * Engine selection and source-text policy for the pipeline.
 * Engine values are inventory IDs; an empty engine ID means use default.
 */
export interface PipelineConfig {
  bubble_segmenter?: string
  detector?: string
  font_detector?: string
  inpainter?: string
  ocr?: string
  renderer?: string
  segmenter?: string
  source_text_policy?: SourceTextPolicy
  translator?: string
  typography_planner?: string
}
