/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export type PipelineStep = (typeof PipelineStep)[keyof typeof PipelineStep]

export const PipelineStep = {
  detect: 'detect',
  ocr: 'ocr',
  inpaint: 'inpaint',
  llmGenerate: 'llmGenerate',
  typography: 'typography',
  render: 'render',
} as const
