/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export type ReadingOrder = (typeof ReadingOrder)[keyof typeof ReadingOrder]

export const ReadingOrder = {
  rtl: 'rtl',
  ltr: 'ltr',
} as const
