/**
 * Generated by orval 🍺
 * Do not edit manually.
 */
import type { DownloadProgress } from './downloadProgress'
import type { JobSummary } from './jobSummary'

export interface SnapshotEvent {
  downloads: DownloadProgress[]
  jobs: JobSummary[]
}
