/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

/**
 * Which OCR text is eligible for translation and image modification.
 */
export type SourceTextPolicy = (typeof SourceTextPolicy)[keyof typeof SourceTextPolicy]

export const SourceTextPolicy = {
  han_only: 'han_only',
  all_text: 'all_text',
} as const
