/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export interface StartDownloadResponse {
  /**
   * Operation id. Reusing the package id keeps ids meaningful for clients
   * watching progress events.
   */
  operationId: string
}
