/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export type TextAlign = (typeof TextAlign)[keyof typeof TextAlign]

export const TextAlign = {
  left: 'left',
  center: 'center',
  right: 'right',
} as const
