/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

/**
 * Typography Planner model selection. Connection details and credentials
 * continue to come from the shared `openai-compatible` provider config.
 */
export interface TypographyPlannerConfig {
  enabled?: boolean
  /** @nullable */
  model_id?: string | null
}
