/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export interface TypographyPlannerConfigPatch {
  /** @nullable */
  enabled?: boolean | null
  /**
   * Outer `Option` means the field is patched; inner `Option` clears or sets it.
   * @nullable
   */
  modelId?: string | null
}
